# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Mars Rovers Photos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mars Rovers Photos
  	pod 'Alamofire', '4.8.0'
  	pod 'ProgressHUD', '~> 2.60'
  	pod 'SDWebImage', '~> 4.0'
    pod 'SwiftyJSON', '~> 4.2'

  target 'Mars Rovers PhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mars Rovers PhotosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
